# Generated by Django 5.2.4 on 2025-07-07 15:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('uploaded', 'Uploaded'), ('viewed', 'Viewed')], max_length=20)),
                ('object_type', models.CharField(choices=[('policy', 'Policy'), ('family_member', 'Family Member'), ('document', 'Document'), ('beneficiary', 'Beneficiary'), ('profile', 'Profile')], max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_policies', models.PositiveIntegerField(default=0)),
                ('active_policies', models.PositiveIntegerField(default=0)),
                ('policies_due_soon', models.PositiveIntegerField(default=0)),
                ('overdue_policies', models.PositiveIntegerField(default=0)),
                ('total_family_members', models.PositiveIntegerField(default=0)),
                ('total_annual_premiums', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_coverage_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_documents', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_summary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Summary',
                'verbose_name_plural': 'Dashboard Summaries',
                'db_table': 'dashboard_summaries',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', max_length=10)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar')], default='USD', max_length=3)),
                ('date_format', models.CharField(default='MM/DD/YYYY', max_length=20)),
                ('show_welcome_message', models.BooleanField(default=True)),
                ('default_dashboard_view', models.CharField(choices=[('summary', 'Summary'), ('policies', 'Policies'), ('calendar', 'Calendar')], default='summary', max_length=20)),
                ('analytics_enabled', models.BooleanField(default=True)),
                ('error_reporting_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
                'db_table': 'user_preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('push', 'Push Notification'), ('sms', 'SMS')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('premium_due_reminder', models.BooleanField(default=True)),
                ('policy_expiry_reminder', models.BooleanField(default=True)),
                ('document_expiry_reminder', models.BooleanField(default=True)),
                ('premium_reminder_days', models.PositiveIntegerField(default=30)),
                ('policy_expiry_reminder_days', models.PositiveIntegerField(default=60)),
                ('document_expiry_reminder_days', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Setting',
                'verbose_name_plural': 'Notification Settings',
                'db_table': 'notification_settings',
                'unique_together': {('user', 'notification_type')},
            },
        ),
    ]
