# Generated by Django 5.2.4 on 2025-07-07 15:21

import django.db.models.deletion
import django.utils.timezone
import policies.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=100)),
                ('policy_type', models.CharField(choices=[('auto', 'Auto Insurance'), ('home', 'Home Insurance'), ('life', 'Life Insurance'), ('health', 'Health Insurance'), ('dental', 'Dental Insurance'), ('vision', 'Vision Insurance'), ('disability', 'Disability Insurance'), ('travel', 'Travel Insurance'), ('pet', 'Pet Insurance'), ('umbrella', 'Umbrella Insurance'), ('renters', 'Renters Insurance'), ('business', 'Business Insurance'), ('other', 'Other')], max_length=20)),
                ('insurer_name', models.CharField(max_length=100)),
                ('insurer_contact_info', models.TextField(blank=True, help_text='Phone, email, address, etc.')),
                ('policy_name', models.CharField(help_text='Custom name for easy identification', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('coverage_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total coverage amount', max_digits=12, null=True)),
                ('deductible', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('premium_amount', models.DecimalField(decimal_places=2, help_text='Premium amount per frequency period', max_digits=10)),
                ('premium_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annually', 'Semi-Annually'), ('annually', 'Annually'), ('one_time', 'One Time')], max_length=20)),
                ('policy_start_date', models.DateField()),
                ('policy_end_date', models.DateField(blank=True, null=True)),
                ('premium_due_date', models.DateField(help_text='Next premium due date')),
                ('last_premium_paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('agent_name', models.CharField(blank=True, max_length=100)),
                ('agent_contact_info', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('notification_days_before', models.PositiveIntegerField(default=30, help_text='Days before premium due date to send notification')),
                ('is_auto_renew', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('policyholder', models.ForeignKey(help_text='The family member who is the primary policyholder', on_delete=django.db.models.deletion.CASCADE, related_name='policies_as_holder', to='family.familymember')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
                'db_table': 'policies',
                'ordering': ['-premium_due_date', 'policy_type', 'insurer_name'],
                'unique_together': {('user', 'policy_number', 'insurer_name')},
            },
        ),
        migrations.CreateModel(
            name='PolicyBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_name', models.CharField(blank=True, max_length=100)),
                ('external_relationship', models.CharField(blank=True, max_length=50)),
                ('external_contact_info', models.TextField(blank=True)),
                ('beneficiary_type', models.CharField(choices=[('primary', 'Primary Beneficiary'), ('contingent', 'Contingent Beneficiary'), ('revocable', 'Revocable Beneficiary'), ('irrevocable', 'Irrevocable Beneficiary')], max_length=20)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Percentage of benefit (e.g., 50.00 for 50%)', max_digits=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('family_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_policies', to='family.familymember')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='policies.policy')),
            ],
            options={
                'verbose_name': 'Policy Beneficiary',
                'verbose_name_plural': 'Policy Beneficiaries',
                'db_table': 'policy_beneficiaries',
                'ordering': ['beneficiary_type', '-percentage'],
            },
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('policy', 'Policy Document'), ('certificate', 'Certificate of Insurance'), ('receipt', 'Premium Payment Receipt'), ('claim', 'Claim Document'), ('correspondence', 'Correspondence'), ('id_card', 'Insurance ID Card'), ('declaration', 'Declaration Page'), ('amendment', 'Policy Amendment'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('document_file', models.FileField(help_text='Supported formats: PDF, JPG, PNG, DOC, DOCX', upload_to=policies.models.policy_document_upload_path)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('document_date', models.DateField(blank=True, help_text='Date the document was created/issued', null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='When this document expires (if applicable)', null=True)),
                ('is_sensitive', models.BooleanField(default=False, help_text='Mark as sensitive for additional security')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='policies.policy')),
            ],
            options={
                'verbose_name': 'Policy Document',
                'verbose_name_plural': 'Policy Documents',
                'db_table': 'policy_documents',
                'ordering': ['-uploaded_at', 'document_type', 'title'],
            },
        ),
    ]
